PROCESS BEFORE OUTPUT.
MODULE STATUS_0100.

PROCESS AFTER INPUT.
MODULE EXIT_CONV_PLAN AT EXIT-COMMAND.
MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD CONVERT_SPEC-NAME MODULE convert_spec_request.

