PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/CIDEON/CSS_CLAS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /CIDEON/CSS_CLAS-ID .
    FIELD /CIDEON/CSS_CLAS-ATNAM .
    FIELD /CIDEON/CSS_CLAS-OPERATOR .
    FIELD /CIDEON/CSS_CLAS-ATWRT .
    FIELD /CIDEON/CSS_CLAS-FIELDMULTI .
    FIELD /CIDEON/CSS_CLAS-FIELDNAME .
    FIELD /CIDEON/CSS_CLAS-FIELDVALUE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /CIDEON/CSS_CLAS-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
