*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 09.06.2004 at 12:22:24 by user KUECHLER
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /CIDEON/LCSS_PFLETOP.              " Global Data
  INCLUDE /CIDEON/LCSS_PFLEUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /CIDEON/LCSS_PFLEF00                    . " subprograms
  INCLUDE /CIDEON/LCSS_PFLEI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /CIDEON/LCSS_PFLEF...              " Subprograms
* INCLUDE /CIDEON/LCSS_PFLEO...              " PBO-Modules
* INCLUDE /CIDEON/LCSS_PFLEI...              " PAI-Modules
