PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /CIDEON/CSS_CLAS-ID .
    FIELD /CIDEON/CSS_CLAS-ATNAM .
    FIELD /CIDEON/CSS_CLAS-OPERATOR .
    FIELD /CIDEON/CSS_CLAS-ATWRT .
    FIELD /CIDEON/CSS_CLAS-FIELDMULTI .
    FIELD /CIDEON/CSS_CLAS-FIELDNAME .
    FIELD /CIDEON/CSS_CLAS-FIELDVALUE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /CIDEON/CSS_CLAS-ID .
  module detail_pai.
 endchain.
