*****           Implementation of object type Z_PLOTADM            *****
INCLUDE <OBJECT>.
BEGIN_DATA OBJECT. " Do not change.. DATA is generated
* only private members may be inserted into structure private
DATA:
" begin of private,
"   to declare private attributes remove comments and
"   insert private attributes here ...
" end of private,
      KEY LIKE SWOTOBJID-OBJKEY.
END_DATA OBJECT. " Do not change.. DATA is generated

BEGIN_METHOD ZCLDOCCHANGEEVENTBATCH CHANGING CONTAINER.
DATA:
      EVENT LIKE SWETYPECOU-EVENT,
      RECTYPE LIKE SWETYPECOU-RECTYPE,
      OBJTYPE LIKE SWETYPECOU-OBJTYPE,
      OBJKEY LIKE SWEINSTCOU-OBJKEY,
      EXCEPTIONSALLOWED LIKE SWEFLAGS-EXC_OK,
      RECID LIKE SWELOG-RECID,
      EVENTCONTAINER LIKE SWCONT OCCURS 0,
      WF_ERZEUGER like wfsyst-agent.                                   .
  SWC_GET_ELEMENT CONTAINER 'Event' EVENT.
  SWC_GET_ELEMENT CONTAINER 'Rectype' RECTYPE.
  SWC_GET_ELEMENT CONTAINER 'Objtype' OBJTYPE.
  SWC_GET_ELEMENT CONTAINER 'Objkey' OBJKEY.
  SWC_GET_ELEMENT CONTAINER 'ExceptionsAllowed' EXCEPTIONSALLOWED.
  IF SY-SUBRC <> 0.
    MOVE SPACE TO EXCEPTIONSALLOWED.
  ENDIF.
  SWC_GET_TABLE CONTAINER 'EventContainer' EVENTCONTAINER.
  swc_get_element container 'Wf_erzeuger' WF_ERZEUGER.
  CALL FUNCTION 'Z_CL_DOC_CHANGE_EVENT_BATCH_02'
    EXPORTING
      EXCEPTIONS_ALLOWED = EXCEPTIONSALLOWED
      OBJKEY = OBJKEY
      OBJTYPE = OBJTYPE
      RECTYPE = RECTYPE
      EVENT = EVENT
      WF_ERZEUGER = WF_ERZEUGER
    IMPORTING
      REC_ID = RECID
    TABLES
      EVENT_CONTAINER = EVENTCONTAINER
    EXCEPTIONS
      ANY_ERROR = 9001
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN 9001.         " ANY_ERROR
      EXIT_RETURN 9001 sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
    WHEN OTHERS.       " to be implemented
  ENDCASE.
  SWC_SET_ELEMENT CONTAINER 'RecId' RECID.
  SWC_SET_TABLE CONTAINER 'EventContainer' EVENTCONTAINER.
END_METHOD.

BEGIN_METHOD ZCLDOCCHANGECHECKBATCH CHANGING CONTAINER.
DATA:
      OBJTYPE LIKE SWETYPECOU-OBJTYPE,
      OBJKEY LIKE SWEINSTCOU-OBJKEY,
      EVENT LIKE SWETYPECOU-EVENT,
      RECTYPE LIKE SWETYPECOU-RECTYPE,
      EVENTCONTAINER LIKE SWCONT OCCURS 0.
  SWC_GET_ELEMENT CONTAINER 'Objtype' OBJTYPE.
  SWC_GET_ELEMENT CONTAINER 'Objkey' OBJKEY.
  SWC_GET_ELEMENT CONTAINER 'Event' EVENT.
  SWC_GET_ELEMENT CONTAINER 'Rectype' RECTYPE.
  SWC_GET_TABLE CONTAINER 'EventContainer' EVENTCONTAINER.
  CALL FUNCTION 'Z_CL_DOC_CHANGE_CHECK_BATCH'
    EXPORTING
      RECTYPE = RECTYPE
      EVENT = EVENT
      OBJKEY = OBJKEY
      OBJTYPE = OBJTYPE
    TABLES
      EVENT_CONTAINER = EVENTCONTAINER
    EXCEPTIONS
      ANY_EXCEPTION = 9001
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN 9001.         " ANY_EXCEPTION
      EXIT_RETURN 9001 sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
    WHEN OTHERS.       " to be implemented
  ENDCASE.
  SWC_SET_TABLE CONTAINER 'EventContainer' EVENTCONTAINER.
END_METHOD.

BEGIN_METHOD EXISTENCECHECK CHANGING CONTAINER.
END_METHOD.

BEGIN_METHOD DISPLAY CHANGING CONTAINER.
END_METHOD.
