PROCESS BEFORE OUTPUT.

  MODULE STATUS_0200.
  MODULE initialize_objstack.

  CALL SUBSCREEN input_mat INCLUDING syst-repid '0201'.
  CALL SUBSCREEN input_doc INCLUDING syst-repid '0202'.

PROCESS AFTER INPUT.

  MODULE exit_0200 AT EXIT-COMMAND.

  CALL SUBSCREEN input_mat.
  CALL SUBSCREEN input_doc.

  MODULE USER_COMMAND_0200.

