PROCESS BEFORE OUTPUT.

  MODULE MODIFY_SCREEN_0202.
  MODULE set_position.
  MODULE SET_SCREEN_FOCUS.

*
PROCESS AFTER INPUT.

  CHAIN.
    FIELD: DRAW-DOKNR,
           DRAW-DOKAR,
           DRAW-DOKTL,
           DRAW-DOKVR MODULE CHECK_DOC_EXIST ON CHAIN-INPUT.
  ENDCHAIN.

  MODULE check_position_fcdoc.

