PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_SCHLUESSEL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_SCHLUESSEL-UNAME .
    FIELD ZCL_SCHLUESSEL-VERTEILER .
    FIELD ZCL_SCHLUESSEL-ID_SCHLUESSEL .
    FIELD ZCL_SCHLUESSEL-PRIO .
    FIELD ZCL_SCHLUESSEL-SCHLUESSSEL .
    FIELD ZCL_SCHLUESSEL-BESCHREIBUNG .
    FIELD ZCL_SCHLUESSEL-ZCLINSNAME .
    FIELD ZCL_SCHLUESSEL-ZCLINSPROG .
    FIELD ZCL_SCHLUESSEL-ZCLUPDNAME .
    FIELD ZCL_SCHLUESSEL-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_SCHLUESSEL-UNAME .
    FIELD ZCL_SCHLUESSEL-VERTEILER .
    FIELD ZCL_SCHLUESSEL-ID_SCHLUESSEL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
