PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_MAIL_CFG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_MAIL_CFG-MSGID .
    FIELD ZCL_MAIL_CFG-MSGNO .
    FIELD ZCL_MAIL_CFG-KNZ_MAIL .
    FIELD ZCL_MAIL_CFG-E_MAIL_ADDR .
    FIELD ZCL_MAIL_CFG-SAP_USER .
    FIELD ZCL_MAIL_CFG-SAP_USR_GROUP .
    FIELD ZCL_MAIL_CFG-ZCLINSNAME .
    FIELD ZCL_MAIL_CFG-ZCLINSPROG .
    FIELD ZCL_MAIL_CFG-ZCLUPDNAME .
    FIELD ZCL_MAIL_CFG-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_MAIL_CFG-MSGID .
    FIELD ZCL_MAIL_CFG-MSGNO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
