PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_USR_HOST_CFG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_USR_HOST_CFG-UNAME .
    FIELD ZCL_USR_HOST_CFG-HOST .
    FIELD ZCL_USR_HOST_CFG-PPL_DOWN_PATH .
    FIELD ZCL_USR_HOST_CFG-DOWN_PATH .
    FIELD ZCL_USR_HOST_CFG-ZCLINSNAME .
    FIELD ZCL_USR_HOST_CFG-ZCLINSPROG .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDNAME .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_USR_HOST_CFG-UNAME .
    FIELD ZCL_USR_HOST_CFG-HOST .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
