PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_USR_GRP_TAB CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_USR_GRP_TAB-SAP_USR_GROUP .
    FIELD ZCL_USR_GRP_TAB-SAP_USER .
    FIELD ZCL_USR_GRP_TAB-STATE .
    FIELD ZCL_USR_GRP_TAB-ZCLINSNAME .
    FIELD ZCL_USR_GRP_TAB-ZCLINSPROG .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDNAME .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_USR_GRP_TAB-SAP_USR_GROUP .
    FIELD ZCL_USR_GRP_TAB-SAP_USER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
