PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZPLINT_USR_TDWP-UNAME .
    FIELD ZPLINT_USR_TDWP-DAPPL .
    FIELD ZPLINT_USR_TDWP-ZCLINSNAME .
    FIELD ZPLINT_USR_TDWP-ZCLINSDATE .
    FIELD ZPLINT_USR_TDWP-ZCLINSTIME .
    FIELD ZPLINT_USR_TDWP-ZCLINSPROG .
    FIELD ZPLINT_USR_TDWP-ZCLUPDNAME .
    FIELD ZPLINT_USR_TDWP-ZCLUPDDATE .
    FIELD ZPLINT_USR_TDWP-ZCLUPDTIME .
    FIELD ZPLINT_USR_TDWP-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZPLINT_USR_TDWP-UNAME .
    FIELD ZPLINT_USR_TDWP-DAPPL .
  module detail_pai.
 endchain.
