PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_BEDING_SET-UNAME .
    FIELD ZCL_BEDING_SET-VERTEILER .
    FIELD ZCL_BEDING_SET-ID_SCHLUESSEL .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG_SUB .
    FIELD ZCL_BEDING_SET-PRIO .
    FIELD ZCL_BEDING_SET-BESCHREIBUNG .
    FIELD ZCL_BEDING_SET-BEDINGUNGSFELD .
    FIELD ZCL_BEDING_SET-OPERATOR .
    FIELD ZCL_BEDING_SET-VERGLEICHSWERT .
    FIELD ZCL_BEDING_SET-ZCLINSNAME .
    FIELD ZCL_BEDING_SET-ZCLINSDATE .
    FIELD ZCL_BEDING_SET-ZCLINSTIME .
    FIELD ZCL_BEDING_SET-ZCLINSPROG .
    FIELD ZCL_BEDING_SET-ZCLUPDNAME .
    FIELD ZCL_BEDING_SET-ZCLUPDDATE .
    FIELD ZCL_BEDING_SET-ZCLUPDTIME .
    FIELD ZCL_BEDING_SET-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_BEDING_SET-UNAME .
    FIELD ZCL_BEDING_SET-VERTEILER .
    FIELD ZCL_BEDING_SET-ID_SCHLUESSEL .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG_SUB .
  module detail_pai.
 endchain.
