PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPLINT_USR_TDWP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPLINT_USR_TDWP-UNAME .
    FIELD ZPLINT_USR_TDWP-DAPPL .
    FIELD ZPLINT_USR_TDWP-ZCLINSNAME .
    FIELD ZPLINT_USR_TDWP-ZCLINSPROG .
    FIELD ZPLINT_USR_TDWP-ZCLUPDNAME .
    FIELD ZPLINT_USR_TDWP-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPLINT_USR_TDWP-UNAME .
    FIELD ZPLINT_USR_TDWP-DAPPL .
*INSERT
    MODULE zcl_plint_usr_tdwp .
    MODULE zcl_plint_routines_pai.
*INSERT ENDE

    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
