PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_SCHLUESSEL-UNAME .
    FIELD ZCL_SCHLUESSEL-VERTEILER .
    FIELD ZCL_SCHLUESSEL-ID_SCHLUESSEL .
    FIELD ZCL_SCHLUESSEL-PRIO .
    FIELD ZCL_SCHLUESSEL-SCHLUESSSEL .
    FIELD ZCL_SCHLUESSEL-BESCHREIBUNG .
    FIELD ZCL_SCHLUESSEL-ZCLINSNAME .
    FIELD ZCL_SCHLUESSEL-ZCLINSDATE .
    FIELD ZCL_SCHLUESSEL-ZCLINSTIME .
    FIELD ZCL_SCHLUESSEL-ZCLINSPROG .
    FIELD ZCL_SCHLUESSEL-ZCLUPDNAME .
    FIELD ZCL_SCHLUESSEL-ZCLUPDDATE .
    FIELD ZCL_SCHLUESSEL-ZCLUPDTIME .
    FIELD ZCL_SCHLUESSEL-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_SCHLUESSEL-UNAME .
    FIELD ZCL_SCHLUESSEL-VERTEILER .
    FIELD ZCL_SCHLUESSEL-ID_SCHLUESSEL .
  module detail_pai.
 endchain.
