PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_PLINT_INI_CF-ZCL_GRUPPE .
    FIELD ZCL_PLINT_INI_CF-ZCL_PNAME .
    FIELD ZCL_PLINT_INI_CF-ZCL_PWERT .
    FIELD ZCL_PLINT_INI_CF-ZCLINSNAME .
    FIELD ZCL_PLINT_INI_CF-ZCLINSDATE .
    FIELD ZCL_PLINT_INI_CF-ZCLINSTIME .
    FIELD ZCL_PLINT_INI_CF-ZCLINSPROG .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDNAME .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDDATE .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDTIME .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_PLINT_INI_CF-ZCL_GRUPPE .
    FIELD ZCL_PLINT_INI_CF-ZCL_PNAME .
  module detail_pai.
 endchain.
