PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_VERTEILER-UNAME .
    FIELD ZCL_VERTEILER-VERTEILER .
    FIELD ZCL_VERTEILER-PRIO .
    FIELD ZCL_VERTEILER-BESCHREIBUNG .
    FIELD ZCL_VERTEILER-ZCLINSNAME .
    FIELD ZCL_VERTEILER-ZCLINSDATE .
    FIELD ZCL_VERTEILER-ZCLINSTIME .
    FIELD ZCL_VERTEILER-ZCLINSPROG .
    FIELD ZCL_VERTEILER-ZCLUPDNAME .
    FIELD ZCL_VERTEILER-ZCLUPDDATE .
    FIELD ZCL_VERTEILER-ZCLUPDTIME .
    FIELD ZCL_VERTEILER-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_VERTEILER-UNAME .
    FIELD ZCL_VERTEILER-VERTEILER .
  module detail_pai.
 endchain.
