PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_VERTEILER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_VERTEILER-UNAME .
    FIELD ZCL_VERTEILER-VERTEILER .
    FIELD ZCL_VERTEILER-PRIO .
    FIELD ZCL_VERTEILER-BESCHREIBUNG .
    FIELD ZCL_VERTEILER-ZCLINSNAME .
    FIELD ZCL_VERTEILER-ZCLINSPROG .
    FIELD ZCL_VERTEILER-ZCLUPDNAME .
    FIELD ZCL_VERTEILER-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_VERTEILER-UNAME .
    FIELD ZCL_VERTEILER-VERTEILER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
