PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_USR_HOST_CFG-UNAME .
    FIELD ZCL_USR_HOST_CFG-HOST .
    FIELD ZCL_USR_HOST_CFG-PPL_DOWN_PATH .
    FIELD ZCL_USR_HOST_CFG-DOWN_PATH .
    FIELD ZCL_USR_HOST_CFG-ZCLINSNAME .
    FIELD ZCL_USR_HOST_CFG-ZCLINSDATE .
    FIELD ZCL_USR_HOST_CFG-ZCLINSTIME .
    FIELD ZCL_USR_HOST_CFG-ZCLINSPROG .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDNAME .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDDATE .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDTIME .
    FIELD ZCL_USR_HOST_CFG-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_USR_HOST_CFG-UNAME .
    FIELD ZCL_USR_HOST_CFG-HOST .
  module detail_pai.
 endchain.
