PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_MAIL_CFG-MSGID .
    FIELD ZCL_MAIL_CFG-MSGNO .
    FIELD ZCL_MAIL_CFG-KNZ_MAIL .
    FIELD ZCL_MAIL_CFG-E_MAIL_ADDR .
    FIELD ZCL_MAIL_CFG-SAP_USER .
    FIELD ZCL_MAIL_CFG-SAP_USR_GROUP .
    FIELD ZCL_MAIL_CFG-ZCLINSNAME .
    FIELD ZCL_MAIL_CFG-ZCLINSDATE .
    FIELD ZCL_MAIL_CFG-ZCLINSTIME .
    FIELD ZCL_MAIL_CFG-ZCLINSPROG .
    FIELD ZCL_MAIL_CFG-ZCLUPDNAME .
    FIELD ZCL_MAIL_CFG-ZCLUPDDATE .
    FIELD ZCL_MAIL_CFG-ZCLUPDTIME .
    FIELD ZCL_MAIL_CFG-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_MAIL_CFG-MSGID .
    FIELD ZCL_MAIL_CFG-MSGNO .
  module detail_pai.
 endchain.
