PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_BEDING_SET CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_BEDING_SET-UNAME .
    FIELD ZCL_BEDING_SET-VERTEILER .
    FIELD ZCL_BEDING_SET-ID_SCHLUESSEL .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG_SUB .
    FIELD ZCL_BEDING_SET-PRIO .
    FIELD ZCL_BEDING_SET-BESCHREIBUNG .
    FIELD ZCL_BEDING_SET-BEDINGUNGSFELD .
    FIELD ZCL_BEDING_SET-OPERATOR .
    FIELD ZCL_BEDING_SET-VERGLEICHSWERT .
    FIELD ZCL_BEDING_SET-ZCLINSNAME .
    FIELD ZCL_BEDING_SET-ZCLINSPROG .
    FIELD ZCL_BEDING_SET-ZCLUPDNAME .
    FIELD ZCL_BEDING_SET-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_BEDING_SET-UNAME .
    FIELD ZCL_BEDING_SET-VERTEILER .
    FIELD ZCL_BEDING_SET-ID_SCHLUESSEL .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG .
    FIELD ZCL_BEDING_SET-ID_BEDINGUNG_SUB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
