PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_BEDINGUNG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_BEDINGUNG-UNAME .
    FIELD ZCL_BEDINGUNG-VERTEILER .
    FIELD ZCL_BEDINGUNG-ID_SCHLUESSEL .
    FIELD ZCL_BEDINGUNG-ID_BEDINGUNG .
    FIELD ZCL_BEDINGUNG-PRIO .
    FIELD ZCL_BEDINGUNG-BESCHREIBUNG .
    FIELD ZCL_BEDINGUNG-DECKBLATT .
    FIELD ZCL_BEDINGUNG-ENDEBLATT .
    FIELD ZCL_BEDINGUNG-KNZ_INHALT_VZ .
    FIELD ZCL_BEDINGUNG-INHALTSBLATT .
    FIELD ZCL_BEDINGUNG-FEHLBLATT .
    FIELD ZCL_BEDINGUNG-VOREINSTELLUNG .
    FIELD ZCL_BEDINGUNG-ZCLINSNAME .
    FIELD ZCL_BEDINGUNG-ZCLINSPROG .
    FIELD ZCL_BEDINGUNG-ZCLUPDNAME .
    FIELD ZCL_BEDINGUNG-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_BEDINGUNG-UNAME .
    FIELD ZCL_BEDINGUNG-VERTEILER .
    FIELD ZCL_BEDINGUNG-ID_SCHLUESSEL .
    FIELD ZCL_BEDINGUNG-ID_BEDINGUNG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
