PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_BEDINGUNG-UNAME .
    FIELD ZCL_BEDINGUNG-VERTEILER .
    FIELD ZCL_BEDINGUNG-ID_SCHLUESSEL .
    FIELD ZCL_BEDINGUNG-ID_BEDINGUNG .
    FIELD ZCL_BEDINGUNG-PRIO .
    FIELD ZCL_BEDINGUNG-BESCHREIBUNG .
    FIELD ZCL_BEDINGUNG-SATZANZAHL .
    FIELD ZCL_BEDINGUNG-DECKBLATT .
    FIELD ZCL_BEDINGUNG-ENDEBLATT .
    FIELD ZCL_BEDINGUNG-KNZ_INHALT_VZ .
    FIELD ZCL_BEDINGUNG-INHALTSBLATT .
    FIELD ZCL_BEDINGUNG-FEHLBLATT .
    FIELD ZCL_BEDINGUNG-VOREINSTELLUNG .
    FIELD ZCL_BEDINGUNG-ZCLINSNAME .
    FIELD ZCL_BEDINGUNG-ZCLINSDATE .
    FIELD ZCL_BEDINGUNG-ZCLINSTIME .
    FIELD ZCL_BEDINGUNG-ZCLINSPROG .
    FIELD ZCL_BEDINGUNG-ZCLUPDNAME .
    FIELD ZCL_BEDINGUNG-ZCLUPDDATE .
    FIELD ZCL_BEDINGUNG-ZCLUPDTIME .
    FIELD ZCL_BEDINGUNG-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_BEDINGUNG-UNAME .
    FIELD ZCL_BEDINGUNG-VERTEILER .
    FIELD ZCL_BEDINGUNG-ID_SCHLUESSEL .
    FIELD ZCL_BEDINGUNG-ID_BEDINGUNG .
  module detail_pai.
 endchain.
