PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZCL_USR_GRP_TAB-SAP_USR_GROUP .
    FIELD ZCL_USR_GRP_TAB-SAP_USER .
    FIELD ZCL_USR_GRP_TAB-STATE .
    FIELD ZCL_USR_GRP_TAB-ZCLINSNAME .
    FIELD ZCL_USR_GRP_TAB-ZCLINSDATE .
    FIELD ZCL_USR_GRP_TAB-ZCLINSTIME .
    FIELD ZCL_USR_GRP_TAB-ZCLINSPROG .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDNAME .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDDATE .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDTIME .
    FIELD ZCL_USR_GRP_TAB-ZCLUPDPROG .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZCL_USR_GRP_TAB-SAP_USR_GROUP .
    FIELD ZCL_USR_GRP_TAB-SAP_USER .
  module detail_pai.
 endchain.
