PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCL_PLINT_INI_CF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCL_PLINT_INI_CF-ZCL_GRUPPE .
    FIELD ZCL_PLINT_INI_CF-ZCL_PNAME .
    FIELD ZCL_PLINT_INI_CF-ZCL_PWERT .
    FIELD ZCL_PLINT_INI_CF-ZCLINSNAME .
    FIELD ZCL_PLINT_INI_CF-ZCLINSDATE .
    FIELD ZCL_PLINT_INI_CF-ZCLINSTIME .
    FIELD ZCL_PLINT_INI_CF-ZCLINSPROG .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDNAME .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDDATE .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDTIME .
    FIELD ZCL_PLINT_INI_CF-ZCLUPDPROG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCL_PLINT_INI_CF-ZCL_GRUPPE .
    FIELD ZCL_PLINT_INI_CF-ZCL_PNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
