class /CIDEON/CL_EX_OM_PS_01 definition
  public
  final
  create public .

*"* public components of class /CIDEON/CL_EX_OM_PS_01
*"* do not include other source files here!!!
public section.

  interfaces /CIDEON/IF_EX_OM_PS_01 .
  type-pools SEEX .
*"* protected components of class /CIDEON/CL_EX_OM_PS_01
*"* do not include other source files here!!!
protected section.
*"* private components of class /CIDEON/CL_EX_OM_PS_01
*"* do not include other source files here!!!
private section.

  type-pools SEEX .
  data INSTANCE_BADI_TABLE type SEEX_EXIT_TAB .
ENDCLASS.



CLASS /CIDEON/CL_EX_OM_PS_01 IMPLEMENTATION.


method /CIDEON/IF_EX_OM_PS_01~CHG_INSERT_DIS_TR.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'SlxZZJbdJ42BYKtpOhXFvm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_INSERT_DIS_TR

       CHANGING
         WA_MDR_TR = WA_MDR_TR
         INSERT_DIS = INSERT_DIS.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'SlxZZJbdJ42BYKtpOhXFvm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_MDF_DATA.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'cWisgTDHTa{qgGTRZK5NRm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_MDF_DATA

       CHANGING
         IT_DOC = IT_DOC
         WA_MDR_TR = WA_MDR_TR
         LT_CONTENTS = LT_CONTENTS
         LT_RANGE_DEF = LT_RANGE_DEF
         DOCUMENT = DOCUMENT
         SHEET = SHEET.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'cWisgTDHTa{qgGTRZK5NRm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_MDR_DIS_DATA_BEFORE_CREATE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'BPvpNq}pHKwVOGXNlYUkrW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_MDR_DIS_DATA_BEFORE_CREATE

       CHANGING
         IT_DOC_DESC = IT_DOC_DESC
         IT_CLASS_ALLOC = IT_CLASS_ALLOC
         IT_CHAR_VAL = IT_CHAR_VAL
         IT_DOC_FILES = IT_DOC_FILES
         DOCUMENTDATA = DOCUMENTDATA.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'BPvpNq}pHKwVOGXNlYUkrW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_MDR_IT_OBJECTS.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'AHNtmazkV42GzrEr0jwdoG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_MDR_IT_OBJECTS

       CHANGING
         IT_OBJECTS = IT_OBJECTS
         WA_MDR_TR = WA_MDR_TR.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'AHNtmazkV42GzrEr0jwdoG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_TR_CLASSDATA.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'QTZ0CFZKhq{Exz{eovUa60'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_TR_CLASSDATA

       CHANGING
         IT_DRAW_ITEM_TR = IT_DRAW_ITEM_TR.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'QTZ0CFZKhq{Exz{eovUa60'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_TR_DIS_DATA_BEFORE_CREATE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'M0Agh9wnTKgQkQWu1LTSlG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_TR_DIS_DATA_BEFORE_CREATE

       CHANGING
         IT_DOC_DESC = IT_DOC_DESC
         IT_CLASS_ALLOC = IT_CLASS_ALLOC
         IT_CHAR_VAL = IT_CHAR_VAL
         IT_DOC_FILES = IT_DOC_FILES
         DOCUMENTDATA = DOCUMENTDATA.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'M0Agh9wnTKgQkQWu1LTSlG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_OM_PS_01~CHG_WA_MDR_TR_DATA_INIT.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_OM_PS_01.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_OM_PS_01' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_OM_PS_01'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'NNANXsG}magRupWVJBjJvW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_WA_MDR_TR_DATA_INIT

       CHANGING
         WA_MDR_TR = WA_MDR_TR.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'NNANXsG}magRupWVJBjJvW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.
ENDCLASS.
