
PROCESS BEFORE OUTPUT.

  MODULE status_0899.
  CALL SUBSCREEN selection_screen_0990 INCLUDING sy-repid '0990'.

*
PROCESS AFTER INPUT.
 CALL SUBSCREEN selection_screen_0990.
 MODULE USER_COMMAND_0899.
