PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'Z100'
  MODULE Z100_INIT.
* MODULE Z100_CHANGE_TC_ATTR.
* MODULE Z100_CHANGE_COL_ATTR.
  LOOP AT   G_Z100_ITAB
       INTO G_Z100_WA
       WITH CONTROL Z100
       CURSOR Z100-CURRENT_LINE.
*   MODULE Z100_CHANGE_FIELD_ATTR
    MODULE Z100_MOVE.
  ENDLOOP.

 MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'Z100'
  LOOP AT G_Z100_ITAB.
    CHAIN.
      FIELD TDWP-DAPPL.
      FIELD TDWP-CVTEXT.
      FIELD TDWP-DATEIFRMT.
      MODULE Z100_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD G_Z100_WA-FLAG
      MODULE Z100_MARK ON REQUEST.
  ENDLOOP.
 MODULE Z100_USER_COMMAND.
* MODULE Z100_CHANGE_TC_ATTR.
* MODULE Z100_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0100.
