FUNCTION-POOL ZIMG.                         "MESSAGE-ID ..

TABLES: DRAW, TDWAT, TDWS, TDWD, TDWE, *TDWE, TDWP, TDWN, TDWX, *TDWD,
        DRAT, IFLO, EQKT, MAKT.

DATA: BEGIN OF INTDRAZ OCCURS 0.
        INCLUDE STRUCTURE DRAZ.
DATA: END OF INTDRAZ.

DATA: BEGIN OF IN_DELDRAD OCCURS 1.
        INCLUDE STRUCTURE DRAD.
DATA: END OF IN_DELDRAD.

DATA: BEGIN OF IN_INTDRAD OCCURS 1.
        INCLUDE STRUCTURE DRAD.
DATA: END OF IN_INTDRAD.

DATA: BEGIN OF IN_MRKDRAD OCCURS 1.
        INCLUDE STRUCTURE DRAD.
DATA: END OF IN_MRKDRAD.

DATA: BEGIN OF IN_UPDDRAD OCCURS 1.
        INCLUDE STRUCTURE DRAD.
DATA: END OF IN_UPDDRAD.

DATA: BEGIN OF IN_UPDDRAP OCCURS 1.
        INCLUDE STRUCTURE DRAP.
DATA: END OF IN_UPDDRAP.

DATA: BEGIN OF IN_DRAP    OCCURS 1.
        INCLUDE STRUCTURE DRAP.
DATA: END OF IN_DRAP.

DATA: BEGIN OF IN_TEXTTAB OCCURS 1.
        INCLUDE STRUCTURE TKTTXT.
DATA: END OF IN_TEXTTAB.

DATA: BEGIN OF OBJECTLINKS OCCURS 100,
        DOKOB LIKE DRAD-DOKOB,
        OBJKY LIKE DRAD-OBJKY,
      END OF OBJECTLINKS.

DATA: BEGIN OF T_SPOPLI OCCURS 100.
        INCLUDE STRUCTURE SPOPLI.
DATA: END OF T_SPOPLI.

DATA: BEGIN OF DRWKY,
        DOKAR LIKE DRAW-DOKAR,
        DOKNR LIKE DRAW-DOKNR,
        DOKTL LIKE DRAW-DOKTL,
        DOKVR LIKE DRAW-DOKVR,
      END OF DRWKY.

DATA: PFAD(140),
      APPLIKATIONSNUMMER,
      APPLIKATIONSTYP,
      PROGRAM LIKE RLGRAP-FILENAME,
      PRG_PATH LIKE RLGRAP-FILENAME,
      COMMANDLINE(2500),
      DOKOB_D(2),
      DOKOB_T(2),
      DOKOB_E(2),
      DOKOB_M(2),
      DOKOB_W(2),
      APP_NAM(30).
