PROCESS BEFORE OUTPUT.
 MODULE STATUS_0550.
 CALL SUBSCREEN PROG_INFO_REF1 including sy-repid '0551'.
 CALL SUBSCREEN PATCH_INFO_REF1 including sy-repid '0552'.
 CALL SUBSCREEN VERSIONS_INFO_REF1 including sy-repid '0553'.
*
PROCESS AFTER INPUT.
 call subscreen PROG_INFO_REF1.
 call subscreen PATCH_INFO_REF1.
 call subscreen VERSIONS_INFO_REF1.
 MODULE USER_COMMAND_0550.
