PROCESS BEFORE OUTPUT.
* PBO FLOW LOGIC FOR TABLECONTROL 'TAB_CNTRL_01'
* MODULE TAB_CNTRL_01_CHANGE_TC_ATTR.
* MODULE TAB_CNTRL_01_CHANGE_COL_ATTR.
  LOOP AT   ITAB_STORED_SEARCH
       INTO WA_STORED_SEARCH
       WITH CONTROL TAB_CNTRL_01
       CURSOR TAB_CNTRL_01-CURRENT_LINE.
    MODULE TAB_CNTRL_01_GET_LINES.
*   MODULE TAB_CNTRL_01_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
* PAI FLOW LOGIC FOR TABLECONTROL 'TAB_CNTRL_01'
  LOOP AT ITAB_STORED_SEARCH.
    FIELD WA_STORED_SEARCH-MARK
      MODULE TAB_CNTRL_01_MARK ON REQUEST.
  ENDLOOP.
  MODULE TAB_CNTRL_01_USER_COMMAND.
* MODULE TAB_CNTRL_01_CHANGE_TC_ATTR.
* MODULE TAB_CNTRL_01_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0100.
