PROCESS BEFORE OUTPUT.
 MODULE STATUS_0102.
 CALL SUBSCREEN TAB1_PL_REF1 including sy-repid '0120'.
 CALL SUBSCREEN TAB2_PL_REF1 including sy-repid '0121'.
 CALL SUBSCREEN TAB3_PL_REF1 including sy-repid '0122'.
 CALL SUBSCREEN TAB4_PL_REF1 including sy-repid '0123'.
 CALL SUBSCREEN TAB5_PL_REF1 including sy-repid '0124'.
 CALL SUBSCREEN TAB6_PL_REF1 including sy-repid '0125'.
 CALL SUBSCREEN TAB7_PL_REF1 including sy-repid '0126'.
 CALL SUBSCREEN TAB8_PL_REF1 including sy-repid '0127'.

*
PROCESS AFTER INPUT.

 CALL SUBSCREEN TAB1_PL_REF1.
 CALL SUBSCREEN TAB2_PL_REF1.
 CALL SUBSCREEN TAB3_PL_REF1.
 CALL SUBSCREEN TAB4_PL_REF1.
 CALL SUBSCREEN TAB5_PL_REF1.
 CALL SUBSCREEN TAB6_PL_REF1.
 CALL SUBSCREEN TAB7_PL_REF1.
 CALL SUBSCREEN TAB8_PL_REF1.
* MODULE USER_COMMAND_0102.
