class /CIDEON/CL_EX_PRE_MAIN_001 definition
  public
  final
  create public .

*"* public components of class /CIDEON/CL_EX_PRE_MAIN_001
*"* do not include other source files here!!!
public section.

  interfaces /CIDEON/IF_EX_PRE_MAIN_001 .
  type-pools SEEX .
*"* protected components of class /CIDEON/CL_EX_PRE_MAIN_001
*"* do not include other source files here!!!
protected section.
*"* private components of class /CIDEON/CL_EX_PRE_MAIN_001
*"* do not include other source files here!!!
private section.

  data INSTANCE_BADI_TABLE type SEEX_EXIT_TAB .
ENDCLASS.



CLASS /CIDEON/CL_EX_PRE_MAIN_001 IMPLEMENTATION.


method /CIDEON/IF_EX_PRE_MAIN_001~ADD_CUSTOMER_FIELDS_SEARCHLIST.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'c0KxN3}qi4I8c8RGGSAh00'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->ADD_CUSTOMER_FIELDS_SEARCHLIST

       CHANGING
         LT_SEARCHLIST = LT_SEARCHLIST.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'c0KxN3}qi4I8c8RGGSAh00'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CFOLDERS_AUSGABE_01.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'VPE41kGcc4k{k{}6DcodJ0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CFOLDERS_AUSGABE_01

       CHANGING
         I_PLOTJOB = I_PLOTJOB
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'VPE41kGcc4k{k{}6DcodJ0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_AFTER_GET_STAMPS.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'J3}mjaoAXa6{CRJ}rreCeW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_AFTER_GET_STAMPS

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         RETURN = RETURN
         ITAB_STAMP_VALUES = ITAB_STAMP_VALUES.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'J3}mjaoAXa6{CRJ}rreCeW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_AT_AUTH_CHECK.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'WIfZvA0wOqYNTijqsfLhb0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_AT_AUTH_CHECK

       CHANGING
         ITAB_SEARCH_TMP = ITAB_SEARCH_TMP.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'WIfZvA0wOqYNTijqsfLhb0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_CLF_DOWNLOAD_URL.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'bSuObc7bJqwBCeDiGdX26m'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_CLF_DOWNLOAD_URL

       CHANGING
         LS_JOB = LS_JOB
         LC_DOWN_PATH = LC_DOWN_PATH
         LC_SKIP = LC_SKIP.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'bSuObc7bJqwBCeDiGdX26m'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_CLF_GHEAD.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'sdzXGla0HaEmU5KrDY4xlm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_CLF_GHEAD
       EXPORTING
         I_PLOTJOB = I_PLOTJOB
       CHANGING
         IT_GHEAD = IT_GHEAD
         IT_STAMPS = IT_STAMPS.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'sdzXGla0HaEmU5KrDY4xlm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_CLF_GROUP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '8eI5DFAqcKsiAwRPhCkipG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_CLF_GROUP

       CHANGING
         ITAB_GROUP_CLF10 = ITAB_GROUP_CLF10
         ITAB_CLFLIST = ITAB_CLFLIST
         ITAB_PLOTLIST = ITAB_PLOTLIST.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '8eI5DFAqcKsiAwRPhCkipG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_CLF_VF.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'qyqMAcuH8KUnRXrkaZrgPG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_CLF_VF

       CHANGING
         ITAB_GROUP_CLF10 = ITAB_GROUP_CLF10
         ITAB_CLFLIST = ITAB_CLFLIST
         ITAB_PLOTLIST = ITAB_PLOTLIST.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'qyqMAcuH8KUnRXrkaZrgPG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_CONF_BEFORE_SEND.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '}pGKgjdVGK6HSsraFuP4D0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_CONF_BEFORE_SEND

       CHANGING
         F_DYN_TOC = F_DYN_TOC
         F_DYN_COV = F_DYN_COV
         LS_USER_DATA = LS_USER_DATA
         LT_PLOTLIST = LT_PLOTLIST.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '}pGKgjdVGK6HSsraFuP4D0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_DIALOG_2D_SPECIAL.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'U4w7XizmGqoczjoUiAQQ1m'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_DIALOG_2D_SPECIAL
       EXPORTING
         I_USER_DATA = I_USER_DATA
       CHANGING
         F_SKIP = F_SKIP
         LT_DRAW = LT_DRAW.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'U4w7XizmGqoczjoUiAQQ1m'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_DIALOG_CV04N.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'L1Lw4tlEw42c3Wf3rA4Ypm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_DIALOG_CV04N

       CHANGING
         F_SKIP = F_SKIP
         LT_DRAW = LT_DRAW.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'L1Lw4tlEw42c3Wf3rA4Ypm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_DIS_DATA_BEFORE_CREATE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'EQrMzewMXakqX26vvSWk8G'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_DIS_DATA_BEFORE_CREATE

       CHANGING
         ID_PLOTJOB_32 = ID_PLOTJOB_32
         IT_OBJECT_LINKS = IT_OBJECT_LINKS
         IT_DOC_DESC = IT_DOC_DESC
         IT_CLASS_ALLOC = IT_CLASS_ALLOC
         IT_CHAR_VAL = IT_CHAR_VAL
         IT_DOC_FILES = IT_DOC_FILES
         DOCUMENTDATA = DOCUMENTDATA.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'EQrMzewMXakqX26vvSWk8G'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_DRAD_OBJ_BEFORE_PRIO.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'OsaSB4QJJqgTXEiz3Qb6}m'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_DRAD_OBJ_BEFORE_PRIO

       CHANGING
         DRAD_OBJECTS = DRAD_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'OsaSB4QJJqgTXEiz3Qb6}m'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_FAUF_CHARGE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'POwMDnpmwaEYItfTjmOO80'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_FAUF_CHARGE
       EXPORTING
         AUFNR = AUFNR
       CHANGING
         CHARG = CHARG.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'POwMDnpmwaEYItfTjmOO80'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_LOG_AT_LOG.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'jl9yCA{TZqMLNXiP}eyMvW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_LOG_AT_LOG

       CHANGING
         PLOT_ITEM = PLOT_ITEM
         LOG_ITEM = LOG_ITEM
         LOG_ITEM_2 = LOG_ITEM_2.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'jl9yCA{TZqMLNXiP}eyMvW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_LOG_AT_SET_ID.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'hUCAMnK3qaAFob4Ik}J6D0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_LOG_AT_SET_ID

       CHANGING
         PLOT_ITEM = PLOT_ITEM
         LOG_ITEM = LOG_ITEM
         LOG_ITEM_2 = LOG_ITEM_2.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'hUCAMnK3qaAFob4Ik}J6D0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_M1_DATE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'by1v0BDPmKwk1jtF35AXGm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_M1_DATE

       CHANGING
         DATE = DATE.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'by1v0BDPmKwk1jtF35AXGm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_M2_DATE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'zzHuSxVJS4{h0y7kNtVj9G'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_M2_DATE

       CHANGING
         DATE = DATE.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'zzHuSxVJS4{h0y7kNtVj9G'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_ME_DOC_DIALOG_EBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'zvIBU3zkUqo5pHh{qxEbgW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_ME_DOC_DIALOG_EBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'zvIBU3zkUqo5pHh{qxEbgW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_ME_DOC_EBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'vlHcwRbR54oU1ZciG3QxV0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_ME_DOC_EBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'vlHcwRbR54oU1ZciG3QxV0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_ME_DOC_MATPOS_EBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'gafhunVIWaQDrADAWFpqoG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_ME_DOC_MATPOS_EBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'gafhunVIWaQDrADAWFpqoG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_ME_DOC_MAT_EBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '6oaZis78fqsK5H31PpyeIm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_ME_DOC_MAT_EBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '6oaZis78fqsK5H31PpyeIm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_ME_START.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '4C2JTVMlJ4I0AmyS0Lzcj0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_ME_START

       CHANGING
         ENT_RETCO = ENT_RETCO
         L_NAST = L_NAST
         CANCEL = CANCEL.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '4C2JTVMlJ4I0AmyS0Lzcj0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_OBJ_AFTER_READ_TMP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'FYhX5Fa1JKYMXVQSJoBsPG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_OBJ_AFTER_READ_TMP

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'FYhX5Fa1JKYMXVQSJoBsPG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_OBJ_AFTER_READ_TMP2.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'bFpxEHwa3qEOa84aj{MMQW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_OBJ_AFTER_READ_TMP2

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'bFpxEHwa3qEOa84aj{MMQW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PLOTLIST_AFTER_SEND.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'G7Nh17U9UKAaS8luLgPZ2W'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PLOTLIST_AFTER_SEND

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'G7Nh17U9UKAaS8luLgPZ2W'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PLOTLIST_AFTER_SEND2.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'N7NxyuRcE4IivOK7kX8VnW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PLOTLIST_AFTER_SEND2

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         ITAB_SEARCHLIST = ITAB_SEARCHLIST
       EXCEPTIONS
         CANCEL =  1.
    case sy-subrc.
      when  1.
        raise CANCEL.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'N7NxyuRcE4IivOK7kX8VnW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PLOTLIST_BEFORE_SEND.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '8eKY9bNc2aIG8z5AwvALFW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PLOTLIST_BEFORE_SEND

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         RETURN = RETURN
         SHOW_MESSAGE = SHOW_MESSAGE.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '8eKY9bNc2aIG8z5AwvALFW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PLOTLIST_BEFORE_SHOW.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'SfjCu{4o3a6LMRC14YSkLW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PLOTLIST_BEFORE_SHOW

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'SfjCu{4o3a6LMRC14YSkLW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PL_EXCL_BT.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'WcpNFVyvBKkMECp9KafCeG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PL_EXCL_BT

       CHANGING
         IT_BT_EX = IT_BT_EX.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'WcpNFVyvBKkMECp9KafCeG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_PL_GLOBAL.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'zJwCK8TI54IFB6S7faRUS0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_PL_GLOBAL

       CHANGING
         LT_PL_GLOBAL = LT_PL_GLOBAL.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'zJwCK8TI54IFB6S7faRUS0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SD_DOC_DIALOG_VBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'T5kozuMOyqkhCiDfxDTf30'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SD_DOC_DIALOG_VBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'T5kozuMOyqkhCiDfxDTf30'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SD_DOC_MATPOS_VBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'W8YnpbRkfaocrROzcZ}}GW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SD_DOC_MATPOS_VBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'W8YnpbRkfaocrROzcZ}}GW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SD_DOC_MAT_VBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'RlXTVYt7WKgJsUITCyxy{G'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SD_DOC_MAT_VBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'RlXTVYt7WKgJsUITCyxy{G'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SD_DOC_VBELNP.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'Fftu6zH24qEZwN5TuE}e8W'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SD_DOC_VBELNP

       CHANGING
         WA_ITEM = WA_ITEM.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'Fftu6zH24qEZwN5TuE}e8W'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SEL_OBJ_BEFORE_PRIO.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'rOZwlDzmH4gw2em33R}yWm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SEL_OBJ_BEFORE_PRIO

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'rOZwlDzmH4gw2em33R}yWm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SEL_OBJ_BEFORE_PROC.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'jWbt0J7fXKQygOT8QNyrcm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SEL_OBJ_BEFORE_PROC

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN
       EXCEPTIONS
         CANCEL =  1.
    case sy-subrc.
      when  1.
        raise CANCEL.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'jWbt0J7fXKQygOT8QNyrcm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SEL_OBJ_BEFORE_WRITE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'gyC6sGDIWaYUi{vFYVqp5G'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SEL_OBJ_BEFORE_WRITE

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'gyC6sGDIWaYUi{vFYVqp5G'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SEL_OBJ_INIT.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'Hsz3cW5nk4Qqxw4B6stlVW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SEL_OBJ_INIT

       CHANGING
         SELECTED_OBJECTS = SELECTED_OBJECTS
         RETURN = RETURN
       EXCEPTIONS
         CANCEL =  1.
    case sy-subrc.
      when  1.
        raise CANCEL.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'Hsz3cW5nk4Qqxw4B6stlVW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SL_EXCL_BT.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'tds4Nwx50K{I}K3lUcIWv0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SL_EXCL_BT

       CHANGING
         IT_BT_EX = IT_BT_EX.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'tds4Nwx50K{I}K3lUcIWv0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SPOOL_DUNNING.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '9NC9{zelGqI14cRHT3T9HW'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SPOOL_DUNNING

       CHANGING
         LS_OUTPUT_OPTIONS = LS_OUTPUT_OPTIONS
         LS_CONTROL_PARAMETERS = LS_CONTROL_PARAMETERS
         FORMNAME = FORMNAME.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '9NC9{zelGqI14cRHT3T9HW'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_SPOOL_PROCESSING.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = '{}QVzKw2dKw5e}BpLEJfc0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_SPOOL_PROCESSING
       EXPORTING
         I_TDOTFTYPE = I_TDOTFTYPE
         I_TDSPOOLID = I_TDSPOOLID
         I_PFAD = I_PFAD
       CHANGING
         O_FILEP = O_FILEP
         F_PROCESSED = F_PROCESSED
       EXCEPTIONS
         ERROR =  1
         NO_SPOOL =  2.
    case sy-subrc.
      when  1.
        raise ERROR.
      when  2.
        raise NO_SPOOL.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = '{}QVzKw2dKw5e}BpLEJfc0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_STOR_SRC_ITEM.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'IgnAQ{ncD4EyTG5SEm97Zm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_STOR_SRC_ITEM

       CHANGING
         WA_STORED_SEARCH = WA_STORED_SEARCH
         WA_SEARCH = WA_SEARCH.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'IgnAQ{ncD4EyTG5SEm97Zm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHG_STPOX_OBJ_BEFORE_PRIO.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'kxNgIuVfmqIzNTVOD5VYs0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHG_STPOX_OBJ_BEFORE_PRIO

       CHANGING
         STPOX_OBJECTS = STPOX_OBJECTS
         RETURN = RETURN.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'kxNgIuVfmqIzNTVOD5VYs0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHK_AUTH_C_DRAW_BGR.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'ogDymyijk42xXdYEkdfzLG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHK_AUTH_C_DRAW_BGR

       CHANGING
         F_USE_STANDARD = F_USE_STANDARD
         F_SUCCESS = F_SUCCESS
         LS_DOCSEARCH = LS_DOCSEARCH.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'ogDymyijk42xXdYEkdfzLG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~CHK_AUTH_SPECIAL.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'ndTxwug5LqIEsIBZ5xZH6W'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHK_AUTH_SPECIAL

       CHANGING
         F_SUCCESS = F_SUCCESS
         LS_DOCSEARCH = LS_DOCSEARCH.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'ndTxwug5LqIEsIBZ5xZH6W'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~SEND_TO_BADI.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'JmmOSY40Lq{bA7e9lUOvMm'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->SEND_TO_BADI

       CHANGING
         IT_NOTIZ = IT_NOTIZ
         IT_STEMPEL_WERT = IT_STEMPEL_WERT
         IT_PLOTJOBS = IT_PLOTJOBS
         IC_STR_PPL_DOWN_PATH = IC_STR_PPL_DOWN_PATH
         IC_STR_DOWN_PATH = IC_STR_DOWN_PATH
         IC_ID_PLOTJOB = IC_ID_PLOTJOB
         IC_PROGRAM = IC_PROGRAM
         IS_DEFAULT_DATA = IS_DEFAULT_DATA
         IS_USER_DATA = IS_USER_DATA
       EXCEPTIONS
         ERROR =  1.
    case sy-subrc.
      when  1.
        raise ERROR.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'JmmOSY40Lq{bA7e9lUOvMm'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~SKIP_MESSAGE_AFTER_SEND.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'bJSNdhSEm4clEMmuzJ3g1W'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->SKIP_MESSAGE_AFTER_SEND

       CHANGING
         ITAB_PLOTLIST = ITAB_PLOTLIST
         ITAB_SEARCHLIST = ITAB_SEARCHLIST
         F_SKIP_MESSAGE = F_SKIP_MESSAGE
       EXCEPTIONS
         CANCEL =  1.
    case sy-subrc.
      when  1.
        raise CANCEL.
    endcase.

    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'bJSNdhSEm4clEMmuzJ3g1W'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method /CIDEON/IF_EX_PRE_MAIN_001~STATUS_CHANGE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO /CIDEON/IF_EX_PRE_MAIN_001.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = '/CIDEON/IF_EX_PRE_MAIN_001' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = '/CIDEON/IF_EX_PRE_MAIN_001'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'v825VMCgDK2I42Oj}DIduG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->STATUS_CHANGE
       EXPORTING
         STATUS = STATUS.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'v825VMCgDK2I42Oj}DIduG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.
ENDCLASS.
