PROCESS BEFORE OUTPUT.
 MODULE STATUS_0101.
* CALL SUBSCREEN TAB_DETAIL_1_REF1 including sy-repid '0110'.
* CALL SUBSCREEN TAB_DETAIL_1_REF2 including sy-repid '0111'.
* CALL SUBSCREEN TAB_DETAIL_1_REF3 including sy-repid '0112'.


*
PROCESS AFTER INPUT.
* CALL SUBSCREEN TAB_DETAIL_1_REF1 .
* CALL SUBSCREEN TAB_DETAIL_1_REF2 .
* CALL SUBSCREEN TAB_DETAIL_1_REF3 .
** MODULE USER_COMMAND_0101.
